---
slug: 'logging'
properties:
  name: 'Logging'
  show_feature_menu_item: false
  storage_key: 'logging' # should correspond exactly to that in the plugin.yaml
# Options Sections
sections:
  -
    slug: 'section_non_ui'
    hidden: true

# Define Options
options:
  -
    key: 'current_plugin_version'
    section: 'section_non_ui'