---
slug: 'logging'
properties:
  name: 'Logging'
  show_feature_menu_item: false
  storage_key: 'logging' # should correspond exactly to that in the plugin.yaml
# Options Sections
sections:
  -
    slug: 'section_non_ui'
    hidden: true

# Define Options
options:
  -
    key: 'enable_logging'
    section: 'section_non_ui'
    type: 'boolean'
    default: true
  -
    key: 'general_logging_table_name'
    section: 'section_non_ui'
    type: 'text'
    value: 'general_logging'
  -
    key: 'current_plugin_version'
    section: 'section_non_ui'