---
name: 'firewall'
# Options Sections
sections:
  -
    slug: 'section_enable_plugin_feature_user_accounts_management'
    primary: true
  -
    slug: 'section_bypass_user_accounts_management'
  -
    slug: 'section_admin_login_notification'
  -
    slug: 'section_user_session_management'
  -
    slug: 'section_non_ui'
    hidden: true

# Define Options
options:
  -
    key: 'enable_user_management'
    section: 'section_enable_plugin_feature_user_accounts_management'
    default: 'N'
    type: 'checkbox'
    link_info: ''
    link_blog: ''
  -
    key: 'enable_xmlrpc_compatibility'
    section: 'section_bypass_user_accounts_management'
    default: 'Y'
    type: 'checkbox'
    link_info: ''
    link_blog: ''
  -
    key: 'enable_admin_login_email_notification'
    section: 'section_admin_login_notification'
    default: 'N'
    type: 'email'
    link_info: 'http://icwp.io/3u'
    link_blog: ''
  -
    key: 'session_timeout_interval'
    section: 'section_user_session_management'
    default: '2'
    type: 'integer'
    link_info: 'http://icwp.io/3x'
    link_blog: ''
  -
    key: 'session_idle_timeout_interval'
    section: 'section_user_session_management'
    default: '0'
    type: 'integer'
    link_info: ''
    link_blog: ''
  -
    key: 'session_lock_location'
    section: 'section_user_session_management'
    default: 'N'
    type: 'checkbox'
    link_info: ''
    link_blog: ''
  -
    key: 'session_username_concurrent_limit'
    section: 'section_user_session_management'
    default: '0'
    type: 'integer'
    link_info: ''
    link_blog: ''
  -
    key: 'session_check_admin_area_only'
    section: 'section_user_session_management'
    default: 'Y'
    type: 'checkbox'
    link_info: ''
    link_blog: ''
  -
    key: 'session_auto_forward_to_admin_area'
    section: 'section_user_session_management'
    default: 'Y'
    type: 'checkbox'
    link_info: ''
    link_blog: ''
  -
    key: 'current_plugin_version'
    section: 'section_non_ui'
  -
    key: 'user_sessions_table_name'
    section: 'section_non_ui'
    value: 'user_management'
  -
    key: 'user_management_table_created'
    section: 'section_non_ui'